name: Build Kernel

on:
  workflow_dispatch:
  
jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        branch: [android13-5.15]

    steps:
    - name: Check Out
      uses: actions/checkout@v4

    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main

    - name: Set TimeZones
      run: |
        sudo timedatectl set-timezone Asia/Bangkok
        sudo dpkg-reconfigure tzdata
        echo "date=$(TZ=Asia/Bangkok date +%Y%m%d-%H%M)"
      continue-on-error: true
        
    - name: Prepare the environment
      run: |
        sudo apt update
        sudo apt -y upgrade
        sudo apt -y install gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib libc6-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libxml2 lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev python3 bc bcc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev openjdk-11-jdk pahole dwarves bc cpio flex bison aptitude git python-is-python3 tar perl wget curl lz4 libelf-dev make aptitude libssl-dev openjdk-11-jdk
        sudo apt -y install pahole libelf-dev
        sudo apt -y install bc cpio flex bison git python-is-python3 tar perl wget curl lz4 libelf-dev
      continue-on-error: true
      
    - name: Setup Aptitude
      run: |
        sudo apt -y install aptitude p7zip-full ccache
        sudo aptitude -y install libssl-dev pahole
      continue-on-error: true
      
    - name: Install OpenJDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
      continue-on-error: true

    - name: Install repo
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo
      continue-on-error: true

    - name: Init Repo
      run: |
        export HOME=${GITHUB_WORKSPACE}
        cd ${GITHUB_WORKSPACE}
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      continue-on-error: true
    
    - name: Clone AnyKernel3
      run: |
        git clone https://github.com/archer0305/AnyKernel3.git AnyKernel3
      continue-on-error: true

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 16
      continue-on-error: true
    
    - name: Clone Kernel Tree & Clang
      run: |
        cd ${GITHUB_WORKSPACE}
        git clone -b ${{ matrix.branch }} --recursive https://github.com/archer0305/kernel_samsung_sm8550-common.git common
        cp -f clang.sh ${GITHUB_WORKSPACE}/common
        cd ${GITHUB_WORKSPACE}/common
        curl -LSs "https://raw.githubusercontent.com/KOWX712/KernelSU/refs/heads/master/kernel/setup.sh" | bash -s master
        chmod +x clang.sh
        ./clang.sh
      continue-on-error: true        
       
    - name: Building Kernel
      run: |
        cd ${GITHUB_WORKSPACE}/common
        export USE_CCACHE=1
        export CCACHE_EXEC=/usr/bin/ccache
        ccache --max-size=50G
        ccache -o compression=true
        export KERNEL_VERSION=$(make kernelversion | awk '/^[0-9]/ {print $1}')
        echo "KERNEL_VERSION=$KERNEL_VERSION" >> $GITHUB_ENV
        chmod +x scripts/build.sh
        export CC="ccache gcc"
        export CXX="ccache g++"
        make clean ARCH=arm64 && make mrproper ARCH=arm64 && rm -rf out/
        ./scripts/build.sh

    - name: Check Ccache
      run: |
        ccache -s
      
    - name: Copy Kernel To Anykernel3
      run: | 
        cd ${GITHUB_WORKSPACE}/common/out/arch/arm64/boot
        cp Image.gz ${GITHUB_WORKSPACE}/AnyKernel3
      continue-on-error: true
     
    - name: Get Kernel version
      run: |
        echo "$KERNEL_VERSION"
      continue-on-error: true

    - name: Packing Zip
      run: |
        cd ${GITHUB_WORKSPACE}/AnyKernel3
        7z a $KERNEL_VERSION.zip *
      continue-on-error: true
  
    - name: Publish to GitHub
      uses: softprops/action-gh-release@v1
      with:
        files: |
          /home/runner/work/Action-Kernel-Builder/Action-Kernel-Builder/AnyKernel3/*.zip
          /home/runner/work/Action-Kernel-Builder/Action-Kernel-Builder/common/out/arch/arm64/boot/Image
          /home/runner/work/Action-Kernel-Builder/Action-Kernel-Builder/common/out/arch/arm64/boot/Image.gz
        name: Release Kernel
        tag_name: ${{ github.run_id }}
        body: |
          ChangeLog :
      env:
        GITHUB_TOKEN: ${{ secrets.TEST }}
      continue-on-error: true   
      
